#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
STATE_FILE="${PART1_GATE_STATE_FILE:-$ROOT/.ops/part1_gate_state.env}"
ESCALATION_THRESHOLD=3

G1_STATUS="Pending"
G2_STATUS="Pending"
G3_STATUS="Pending"
G4_STATUS="Pending"
G5_STATUS="Pending"
TOTAL_RETRIES=0
RETRY_CODE=0
RETRY_ENV=0
RETRY_DATA=0
RETRY_PROCEDURE=0
LAST_RETRY_CAUSE=""
LAST_RETRY_AT=""
ESCALATED=0
ESCALATED_AT=""
LAST_UPDATED_AT=""

log() {
  printf '%s\n' "$*"
}

usage() {
  cat <<EOF
Usage:
  $(basename "$0") <command> [args]

Part1 Gate Commands:
  init [--force]
      Initialize the gate state file.

  set-status <G1|G2|G3|G4|G5> <Pass|Fail|Pending>
      Update one gate status.

  add-retry <code|env|data|procedure>
      Increment retry counters and track cause.

  show-board
      Display gate board, retry totals, and escalation status.

  check-lock
      Exit 0 when G1..G5 are all Pass; otherwise exit 1.

  check-escalation
      Exit 0 when retries reached escalation threshold (${ESCALATION_THRESHOLD});
      otherwise exit 1.

  help
      Show this help text.

State File:
  ${STATE_FILE}
  Override with environment variable: PART1_GATE_STATE_FILE

Examples:
  $(basename "$0") init
  $(basename "$0") set-status G1 Pass
  $(basename "$0") add-retry env
  $(basename "$0") show-board
  $(basename "$0") check-lock
  $(basename "$0") check-escalation
EOF
}

utc_now() {
  date -u +"%Y-%m-%dT%H:%M:%SZ"
}

ensure_state_dir() {
  mkdir -p "$(dirname "$STATE_FILE")"
}

is_non_negative_int() {
  [[ "$1" =~ ^[0-9]+$ ]]
}

is_valid_status() {
  case "$1" in
    Pass|Fail|Pending) return 0 ;;
    *) return 1 ;;
  esac
}

normalize_status() {
  local value="${1:-}"
  case "${value,,}" in
    pass) printf 'Pass' ;;
    fail) printf 'Fail' ;;
    pending) printf 'Pending' ;;
    *) return 1 ;;
  esac
}

normalize_cause() {
  local value="${1:-}"
  case "${value,,}" in
    code|env|data|procedure) printf '%s' "${value,,}" ;;
    *) return 1 ;;
  esac
}

set_defaults() {
  G1_STATUS="Pending"
  G2_STATUS="Pending"
  G3_STATUS="Pending"
  G4_STATUS="Pending"
  G5_STATUS="Pending"
  TOTAL_RETRIES=0
  RETRY_CODE=0
  RETRY_ENV=0
  RETRY_DATA=0
  RETRY_PROCEDURE=0
  LAST_RETRY_CAUSE=""
  LAST_RETRY_AT=""
  ESCALATED=0
  ESCALATED_AT=""
  LAST_UPDATED_AT="$(utc_now)"
}

apply_escalation_policy() {
  if (( TOTAL_RETRIES >= ESCALATION_THRESHOLD )); then
    if (( ESCALATED == 0 )); then
      ESCALATED=1
      if [[ -z "$ESCALATED_AT" ]]; then
        ESCALATED_AT="$(utc_now)"
      fi
    fi
  else
    ESCALATED=0
    ESCALATED_AT=""
  fi
}

save_state() {
  ensure_state_dir
  LAST_UPDATED_AT="$(utc_now)"
  apply_escalation_policy

  local tmp_file="${STATE_FILE}.tmp"
  cat > "$tmp_file" <<EOF
# Auto-generated by scripts/request2_part1_gate_ops.sh
G1=${G1_STATUS}
G2=${G2_STATUS}
G3=${G3_STATUS}
G4=${G4_STATUS}
G5=${G5_STATUS}
TOTAL_RETRIES=${TOTAL_RETRIES}
RETRY_CODE=${RETRY_CODE}
RETRY_ENV=${RETRY_ENV}
RETRY_DATA=${RETRY_DATA}
RETRY_PROCEDURE=${RETRY_PROCEDURE}
LAST_RETRY_CAUSE=${LAST_RETRY_CAUSE}
LAST_RETRY_AT=${LAST_RETRY_AT}
ESCALATED=${ESCALATED}
ESCALATED_AT=${ESCALATED_AT}
LAST_UPDATED_AT=${LAST_UPDATED_AT}
EOF
  mv "$tmp_file" "$STATE_FILE"
}

validate_loaded_state() {
  local status
  for status in "$G1_STATUS" "$G2_STATUS" "$G3_STATUS" "$G4_STATUS" "$G5_STATUS"; do
    if ! is_valid_status "$status"; then
      log "Invalid gate status found in state file: ${status}"
      log "Run: $(basename "$0") init --force"
      return 1
    fi
  done

  local counter
  for counter in "$TOTAL_RETRIES" "$RETRY_CODE" "$RETRY_ENV" "$RETRY_DATA" "$RETRY_PROCEDURE" "$ESCALATED"; do
    if ! is_non_negative_int "$counter"; then
      log "Invalid counter found in state file: ${counter}"
      log "Run: $(basename "$0") init --force"
      return 1
    fi
  done

  if (( RETRY_CODE + RETRY_ENV + RETRY_DATA + RETRY_PROCEDURE != TOTAL_RETRIES )); then
    log "Retry counters are inconsistent in state file."
    log "Run: $(basename "$0") init --force"
    return 1
  fi

  if (( ESCALATED > 1 )); then
    log "Invalid escalation flag found in state file: ${ESCALATED}"
    log "Run: $(basename "$0") init --force"
    return 1
  fi

  return 0
}

load_state() {
  if [[ ! -f "$STATE_FILE" ]]; then
    set_defaults
    save_state
    return 0
  fi

  set_defaults

  local key value
  while IFS='=' read -r key value; do
    [[ -z "${key}" ]] && continue
    [[ "${key:0:1}" == "#" ]] && continue
    case "$key" in
      G1) G1_STATUS="$value" ;;
      G2) G2_STATUS="$value" ;;
      G3) G3_STATUS="$value" ;;
      G4) G4_STATUS="$value" ;;
      G5) G5_STATUS="$value" ;;
      TOTAL_RETRIES) TOTAL_RETRIES="$value" ;;
      RETRY_CODE) RETRY_CODE="$value" ;;
      RETRY_ENV) RETRY_ENV="$value" ;;
      RETRY_DATA) RETRY_DATA="$value" ;;
      RETRY_PROCEDURE) RETRY_PROCEDURE="$value" ;;
      LAST_RETRY_CAUSE) LAST_RETRY_CAUSE="$value" ;;
      LAST_RETRY_AT) LAST_RETRY_AT="$value" ;;
      ESCALATED) ESCALATED="$value" ;;
      ESCALATED_AT) ESCALATED_AT="$value" ;;
      LAST_UPDATED_AT) LAST_UPDATED_AT="$value" ;;
      *)
        ;;
    esac
  done < "$STATE_FILE"

  validate_loaded_state
}

all_gates_pass() {
  [[ "$G1_STATUS" == "Pass" ]] &&
    [[ "$G2_STATUS" == "Pass" ]] &&
    [[ "$G3_STATUS" == "Pass" ]] &&
    [[ "$G4_STATUS" == "Pass" ]] &&
    [[ "$G5_STATUS" == "Pass" ]]
}

cmd_init() {
  local force="${1:-}"
  if [[ -f "$STATE_FILE" && "$force" != "--force" ]]; then
    log "State file already exists: $STATE_FILE"
    log "Use '$(basename "$0") init --force' to reset it."
    return 0
  fi

  set_defaults
  save_state
  log "Initialized gate state: $STATE_FILE"
}

cmd_set_status() {
  local gate="${1:-}"
  local raw_status="${2:-}"

  if [[ -z "$gate" || -z "$raw_status" ]]; then
    log "Usage: $(basename "$0") set-status <G1|G2|G3|G4|G5> <Pass|Fail|Pending>"
    return 2
  fi

  local status
  if ! status="$(normalize_status "$raw_status")"; then
    log "Invalid status '$raw_status'. Use: Pass, Fail, or Pending."
    return 2
  fi

  case "$gate" in
    G1|G2|G3|G4|G5)
      ;;
    *)
      log "Invalid gate '$gate'. Use one of: G1, G2, G3, G4, G5."
      return 2
      ;;
  esac

  load_state

  case "$gate" in
    G1) G1_STATUS="$status" ;;
    G2) G2_STATUS="$status" ;;
    G3) G3_STATUS="$status" ;;
    G4) G4_STATUS="$status" ;;
    G5) G5_STATUS="$status" ;;
  esac

  save_state
  log "Updated ${gate}=${status}"

  if all_gates_pass; then
    log "Part2 lock: OPEN (G1..G5 all Pass)"
  else
    log "Part2 lock: CLOSED (at least one gate is not Pass)"
  fi
}

cmd_add_retry() {
  local raw_cause="${1:-}"
  if [[ -z "$raw_cause" ]]; then
    log "Usage: $(basename "$0") add-retry <code|env|data|procedure>"
    return 2
  fi

  local cause
  if ! cause="$(normalize_cause "$raw_cause")"; then
    log "Invalid retry cause '$raw_cause'. Use: code, env, data, or procedure."
    return 2
  fi

  load_state

  TOTAL_RETRIES=$((TOTAL_RETRIES + 1))
  case "$cause" in
    code) RETRY_CODE=$((RETRY_CODE + 1)) ;;
    env) RETRY_ENV=$((RETRY_ENV + 1)) ;;
    data) RETRY_DATA=$((RETRY_DATA + 1)) ;;
    procedure) RETRY_PROCEDURE=$((RETRY_PROCEDURE + 1)) ;;
  esac
  LAST_RETRY_CAUSE="$cause"
  LAST_RETRY_AT="$(utc_now)"

  save_state

  log "Recorded retry #${TOTAL_RETRIES} (cause=${cause})."
  if (( TOTAL_RETRIES >= ESCALATION_THRESHOLD )); then
    log "ESCALATION REQUIRED: retries reached ${TOTAL_RETRIES} (threshold=${ESCALATION_THRESHOLD})."
  else
    local remaining=$((ESCALATION_THRESHOLD - TOTAL_RETRIES))
    log "Escalation not required yet: ${remaining} retries remaining."
  fi
}

cmd_show_board() {
  load_state

  printf 'Part1 Gate Board\n'
  printf 'State file: %s\n' "$STATE_FILE"
  printf 'Last updated: %s\n' "${LAST_UPDATED_AT:-unknown}"
  printf '\n'
  printf '%-4s %-8s\n' "Gate" "Status"
  printf '%-4s %-8s\n' "G1" "$G1_STATUS"
  printf '%-4s %-8s\n' "G2" "$G2_STATUS"
  printf '%-4s %-8s\n' "G3" "$G3_STATUS"
  printf '%-4s %-8s\n' "G4" "$G4_STATUS"
  printf '%-4s %-8s\n' "G5" "$G5_STATUS"
  printf '\n'
  printf 'Retries total: %d (threshold=%d)\n' "$TOTAL_RETRIES" "$ESCALATION_THRESHOLD"
  printf '  code: %d\n' "$RETRY_CODE"
  printf '  env: %d\n' "$RETRY_ENV"
  printf '  data: %d\n' "$RETRY_DATA"
  printf '  procedure: %d\n' "$RETRY_PROCEDURE"
  if [[ -n "$LAST_RETRY_CAUSE" ]]; then
    printf 'Last retry: cause=%s at %s\n' "$LAST_RETRY_CAUSE" "$LAST_RETRY_AT"
  fi

  if (( TOTAL_RETRIES >= ESCALATION_THRESHOLD )); then
    printf 'Escalation: REQUIRED (since %s)\n' "${ESCALATED_AT:-unknown}"
  else
    local remaining=$((ESCALATION_THRESHOLD - TOTAL_RETRIES))
    printf 'Escalation: not required (%d retries remaining)\n' "$remaining"
  fi

  if all_gates_pass; then
    printf 'Part2 lock: OPEN\n'
  else
    printf 'Part2 lock: CLOSED\n'
  fi
}

cmd_check_lock() {
  load_state
  if all_gates_pass; then
    log "Part2 lock OPEN: G1..G5 are all Pass."
    return 0
  fi

  log "Part2 lock CLOSED: all gates must be Pass."
  return 1
}

cmd_check_escalation() {
  load_state
  if (( TOTAL_RETRIES >= ESCALATION_THRESHOLD )); then
    log "ESCALATION REQUIRED: retries=${TOTAL_RETRIES}, threshold=${ESCALATION_THRESHOLD}."
    return 0
  fi

  local remaining=$((ESCALATION_THRESHOLD - TOTAL_RETRIES))
  log "Escalation not required: retries=${TOTAL_RETRIES}, remaining=${remaining}."
  return 1
}

main() {
  local command="${1:-help}"
  shift || true

  case "$command" in
    init)
      cmd_init "${1:-}"
      ;;
    set-status|set-gate)
      cmd_set_status "${1:-}" "${2:-}"
      ;;
    add-retry|retry)
      cmd_add_retry "${1:-}"
      ;;
    show-board|board|status)
      cmd_show_board
      ;;
    check-lock|lock)
      cmd_check_lock
      ;;
    check-escalation|escalation)
      cmd_check_escalation
      ;;
    help|-h|--help)
      usage
      ;;
    *)
      log "Unknown command: $command"
      usage
      return 2
      ;;
  esac
}

main "$@"
